### ISSUE TITLE
Support for black cards with two / three blanks

### ISSUE THREAD

**Issue by F1nnM** [F1nnM/Yet-another-Cards-Against-Humanity-clone#3]
# Todo
- [ ] Allow to play multiple white cards, if black card has multiple gaps
- [ ] Display multiple cards nicely
- [ ] Draw more cards (+1 for two gaps, +2 for three)
